server:
  port: 8082

spring:
  application:
    name: client-api
  config:
    import: configserver:http://localhost:8081

logging:
  level:
    org:
      springframework:
        cloud: info

application:
  config:
    refresh:
      auto:
        enabled: false